project:
  type: book

book:
  title: "Data Analysis for Journalism and Political Communication"
  author: "Nicholas Bell, Ph.D."
  chapters:
    - index.qmd
    - part: "Data Generating Process"
      chapters:
        - data_generating_process/researcher_choices.qmd
        - data_generating_process/operationalization.qmd
    
format:
  html:
    theme: yeti
    css: styles.css
    footnotes-hover: true
    link-external-newwindow: true



