project:
  type: book

book:
  title: "Data Analysis for Journalism and Political Communication"
  author: "Nicholas Bell, Ph.D."
  chapters:
    - index.qmd
    # - operationalization.qmd
    
format:
  html:
    theme: yeti
    css: styles.css
    footnotes-hover: true



