# Operationalization

One of the most cited articles in political science is by James Fearon and David Laitin and concerns the causes of civil war. The authors argue that a country's vulnerability to insurgency^[Defined as "military conflict characterized by small, lightly armed bands practicing guerrilla warfare from rural base areas."] explains the likelihood that a country ends up in civil war.

Let's put ourselves in the shoes of the authors. If we want to observe the correlation between civil wars and "vulnerability to insurgency," we need a quantifiable measure that we can use in our analysis. How do we find such a measure? Fearon and Laitin actually propose XX measures of "vulnerability to insurgency":

For now, let's focus on just one: rough terrain. Certainly rough terrain is more measurable than vulnerability to insurgency, but the researcher must still make important choices. How "rough" must the ground be to qualify as rough terrain? Will we measure roughness in degrees (e.g., on a scale from 1-100) or as categories (flat, somewhat rough, or very rough)? What is the unit of geography for which we will measure roughness? If a town lies in a flat valley surrounded by rocky, steep hills, is that considered rough terrain?

Fearon and Laitin ultimately chose to measure rough terrain as the proportion of the country that is "mountainous," as determined by the geographer A.J. Gerard. Still, there are questions about Gerard's measure. When does a hill become a mountain (the subject of a 1995 film starring Hugh Grant, *The Englishman Who Went Up a Hill But Came down a Mountain*)? Does it matter if the mountain is accessible, with roads and trails, or covered in rocks and dense forest? Are mountain ranges better or worse for insurgency compared to mountains that stand alone?

Although I am picking on Fearon and Laitin a bit here, in truth, it is *very* difficult to find good measures for most of the concepts in which we are interested when conducting data analysis. Researchers try their best to come up with measures that are concise and unambiguous, but often we are just doing the best we can with the resources that we have. As long as we are upfront with our readers, we can generally accept the limitations of our measures and move on. For example, Fearon and Laitin write,

> [Mountainous terrain] does not pick up other sorts of rough terrain that can be favorable to guerrillas such as swamps and jungle, and it takes no account of population distributions or food availability in relation to mountains; but it is the best we have been able to do.

We run into this problem all the time. For example, Freedom House.